# Generated by Django 3.0.6 on 2020-05-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20200509_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='apartment',
            new_name='apa',
        ),
    ]
