# Generated by Django 3.0.6 on 2020-05-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_auto_20200524_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='apa',
            new_name='apartment',
        ),
    ]
