# Generated by Django 3.0.6 on 2020-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'guest'), ('host', 'host'), ('costumer', 'costumer')], default='guest', max_length=10),
        ),
    ]
